language: node_js

branches:
  only:
    - gh-pages

env:
  global:
    - URL="https://w3c.github.io/mediacapture-image/W3CTRMANIFEST"
    - DECISION="https://lists.w3.org/Archives/Public/public-media-capture/2015Dec/0031.html"
    - secure: "dSSjBZ8tQhTxMPAjSycyt0JRns20fFwe/2FIQ0UncQYaNLvjTv7RUaetYDfl+nMDettZwaiwJ21qmHagp/Bcm/m+QzWtSSr+a1IsSpWG2s2JaBYJvCmdebpjN1if7l36Dq/1tisdIEImagBCDGymvVMUMt2n9QRp6zZN2VDiRgY="

script:
  - echo "ok"

after_success:
  - test $TRAVIS_PULL_REQUEST = false && curl "https://labs.w3.org/echidna/api/request" --data "url=$URL" --data "decision=$DECISION" --data "token=$TOKEN"'
